#!/bin/sh

curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/01.Gen.1.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/02.Gen.2.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/03.Exod.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/04.Lev.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/05.Num.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/06.Deut.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/07.JoshB.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/08.JoshA.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/09.JudgesB.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/10.JudgesA.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/11.Ruth.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/12.1Sam.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/13.2Sam.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/14.1Kings.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/15.2Kings.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/16.1Chron.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/17.2Chron.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/18.1Esdras.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/19.2Esdras.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/20.Esther.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/21.Judith.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/22.TobitBA.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/23.TobitS.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/24.1Macc.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/25.2Macc.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/26.3Macc.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/27.4Macc.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/28.Psalms1.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/29.Psalms2.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/30.Odes.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/31.Proverbs.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/32.Qoheleth.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/33.Canticles.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/34.Job.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/35.Wisdom.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/36.Sirach.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/37.PsSol.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/38.Hosea.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/39.Micah.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/40.Amos.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/41.Joel.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/42.Jonah.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/43.Obadiah.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/44.Nahum.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/45.Habakkuk.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/46.Zeph.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/47.Haggai.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/48.Zech.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/49.Malachi.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/50.Isaiah1.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/51.Isaiah2.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/52.Jer1.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/53.Jer2.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/54.Baruch.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/55.EpJer.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/56.Lam.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/57.Ezek1.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/58.Ezek2.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/59.BelOG.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/60.BelTh.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/61.DanielOG.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/62.DanielTh.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/63.SusOG.mlxx
curl -O https://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/64.SusTh.mlxx
