name: Module Tests

on:
  push: 
    branches: [master, restricted, experimental]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test Modules
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - run: zig build test

